version: "3.3"

application:
  author: "Angelos Giannis"
  name: "GitPullRequests"
  usage: "CLI tool to check status of pull requests in github, get pull requests of users and extract metrics on them."
  version: "0.0.2"
clients:
  github:
    api_url: "https://api.github.com"
    token:
      default_env_var: "GITPR_GITHUB_AUTH_TOKEN"
      default_value: ""
    endpoints:
      get_commit_details: "/repos/{repoOwner}/{repository}/commits/{commitSha}"
      get_diff_between_tags: "/repos/{repoOwner}/{repository}/compare/{existingTag}...{newTag}"
      get_pull_request_commits: "/repos/{repoOwner}/{repository}/pulls/{pullRequestNumber}/commits?per_page={pageSize}&page={pageNumber}"
      get_pull_request_details: "/repos/{repoOwner}/{repository}/pulls/{pullRequestNumber}"
      get_release_list: "/repos/{repoOwner}/{repository}/releases?per_page={pageSize}&page={pageNumber}"
      get_review_status_of_pull_request: "/repos/{repoOwner}/{repository}/pulls/{pullRequestNumber}/reviews"
      get_user_repos: "/user/repos?per_page={pageSize}&page={pageNumber}"
      get_user_pull_requests_for_repo: "/repos/{repoOwner}/{repository}/pulls?state={prState}&per_page={pageSize}&page={pageNumber}&{baseBranch}&sort=created&direction=desc"
      post_create_release: "/repos/{repoOwner}/{repository}/releases"
      get_workflow_details: "/repos/{repoOwner}/{repository}/actions/runs?created={createdFrom}..{createdTo}&per_page={pageSize}&page={pageNumber}&status=completed"
      get_workflows_of_repository: "/repos/{repoOwner}/{repository}/actions/workflows?page=1&per_page=100"
      get_workflow_execution_timing: "/repos/{repoOwner}/{repository}/actions/runs/{run_id}/timing"
      get_workflow_usage: "/repos/{repoOwner}/{repository}/actions/workflows/{workflowID}/timing"
    headers:
      accept: "application/vnd.github.sailor-v-preview+json"
    billing:
      linux: 0.008
      macOS: 0.08
      windows: 0.016
pagination:
  next: "Next"
  previous: "Previous"
  exit: "Exit"
service:
  mode: "{serviceMode}"
  port: "{servicePort}"
settings:
  allowed_pull_request_states: ["all", "open", "closed"]
  available_clients: ["github"]
  base_branch: "master"
  default_client: "github"
  page_size: 0
  pull_request_state: "open"
spinner:
  hide_cursor: true
  type: 35
  time: 200
